version: '3'
services:
  quark:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
  # Uncomment when the implemetation is ready
  #  depends_on:
  #   - db
  #db:
  #  image: "mongo"
  #redis:
  #  image: "redis"
